services:
  app:
    #build: .
    image: ghcr.io/koyuspace/client:latest
    container_name: koyuspace-client
    ports:
      - "3030:3030"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3030
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
